joy_node:
    ros__parameters:
        device_id: 1
        device_name: "Logitech Logitech(R) Precision(TM) Gamepad"
        deadzone: 0.5
        autorepeat_rate: 20.0
        sticky_buttons: false
        coalesce_interval_ms: 1
